
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/intel/oneapi/tbb/2022.0/bin/"
      - "/opt/intel/oneapi/tbb/2022.0/sbin/"
      - "/opt/intel/oneapi/tbb/2022.0/"
      - "/opt/intel/oneapi/pti/0.10/lib/cmake/pti/bin/"
      - "/opt/intel/oneapi/pti/0.10/lib/cmake/pti/sbin/"
      - "/opt/intel/oneapi/pti/0.10/lib/cmake/pti/"
      - "/opt/intel/oneapi/mkl/2025.0/lib/cmake/bin/"
      - "/opt/intel/oneapi/mkl/2025.0/lib/cmake/sbin/"
      - "/opt/intel/oneapi/mkl/2025.0/lib/cmake/"
      - "/opt/intel/oneapi/ipp/2022.0/lib/cmake/ipp/bin/"
      - "/opt/intel/oneapi/ipp/2022.0/lib/cmake/ipp/sbin/"
      - "/opt/intel/oneapi/ipp/2022.0/lib/cmake/ipp/"
      - "/opt/intel/oneapi/dpl/2022.7/lib/cmake/oneDPL/bin/"
      - "/opt/intel/oneapi/dpl/2022.7/lib/cmake/oneDPL/sbin/"
      - "/opt/intel/oneapi/dpl/2022.7/lib/cmake/oneDPL/"
      - "/opt/intel/oneapi/dnnl/2025.0/lib/cmake/bin/"
      - "/opt/intel/oneapi/dnnl/2025.0/lib/cmake/sbin/"
      - "/opt/intel/oneapi/dnnl/2025.0/lib/cmake/"
      - "/opt/intel/oneapi/dal/2025.0/bin/"
      - "/opt/intel/oneapi/dal/2025.0/sbin/"
      - "/opt/intel/oneapi/dal/2025.0/"
      - "/opt/intel/oneapi/compiler/2025.0/bin/"
      - "/opt/intel/oneapi/compiler/2025.0/sbin/"
      - "/opt/intel/oneapi/compiler/2025.0/"
      - "/home/mike/.cargo/bin/"
      - "/opt/intel/oneapi/vtune/2025.0/bin64/"
      - "/opt/intel/oneapi/mpi/2021.14/bin/"
      - "/opt/intel/oneapi/mkl/2025.0/bin/"
      - "/opt/intel/oneapi/dpcpp-ct/2025.0/bin/"
      - "/opt/intel/oneapi/dev-utilities/2025.0/bin/"
      - "/opt/intel/oneapi/debugger/2025.0/opt/debugger/bin/"
      - "/opt/intel/oneapi/compiler/2025.0/bin/"
      - "/opt/intel/oneapi/advisor/2025.0/bin64/"
      - "/home/mike/miniconda3/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/snap/bin/"
    searched_directories:
      - "/opt/intel/oneapi/tbb/2022.0/bin/uname"
      - "/opt/intel/oneapi/tbb/2022.0/sbin/uname"
      - "/opt/intel/oneapi/tbb/2022.0/uname"
      - "/opt/intel/oneapi/pti/0.10/lib/cmake/pti/bin/uname"
      - "/opt/intel/oneapi/pti/0.10/lib/cmake/pti/sbin/uname"
      - "/opt/intel/oneapi/pti/0.10/lib/cmake/pti/uname"
      - "/opt/intel/oneapi/mkl/2025.0/lib/cmake/bin/uname"
      - "/opt/intel/oneapi/mkl/2025.0/lib/cmake/sbin/uname"
      - "/opt/intel/oneapi/mkl/2025.0/lib/cmake/uname"
      - "/opt/intel/oneapi/ipp/2022.0/lib/cmake/ipp/bin/uname"
      - "/opt/intel/oneapi/ipp/2022.0/lib/cmake/ipp/sbin/uname"
      - "/opt/intel/oneapi/ipp/2022.0/lib/cmake/ipp/uname"
      - "/opt/intel/oneapi/dpl/2022.7/lib/cmake/oneDPL/bin/uname"
      - "/opt/intel/oneapi/dpl/2022.7/lib/cmake/oneDPL/sbin/uname"
      - "/opt/intel/oneapi/dpl/2022.7/lib/cmake/oneDPL/uname"
      - "/opt/intel/oneapi/dnnl/2025.0/lib/cmake/bin/uname"
      - "/opt/intel/oneapi/dnnl/2025.0/lib/cmake/sbin/uname"
      - "/opt/intel/oneapi/dnnl/2025.0/lib/cmake/uname"
      - "/opt/intel/oneapi/dal/2025.0/bin/uname"
      - "/opt/intel/oneapi/dal/2025.0/sbin/uname"
      - "/opt/intel/oneapi/dal/2025.0/uname"
      - "/opt/intel/oneapi/compiler/2025.0/bin/uname"
      - "/opt/intel/oneapi/compiler/2025.0/sbin/uname"
      - "/opt/intel/oneapi/compiler/2025.0/uname"
      - "/home/mike/.cargo/bin/uname"
      - "/opt/intel/oneapi/vtune/2025.0/bin64/uname"
      - "/opt/intel/oneapi/mpi/2021.14/bin/uname"
      - "/opt/intel/oneapi/mkl/2025.0/bin/uname"
      - "/opt/intel/oneapi/dpcpp-ct/2025.0/bin/uname"
      - "/opt/intel/oneapi/dev-utilities/2025.0/bin/uname"
      - "/opt/intel/oneapi/debugger/2025.0/opt/debugger/bin/uname"
      - "/opt/intel/oneapi/compiler/2025.0/bin/uname"
      - "/opt/intel/oneapi/advisor/2025.0/bin64/uname"
      - "/home/mike/miniconda3/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{CMAKE_PREFIX_PATH}:
        - "/opt/intel/oneapi/tbb/2022.0/env/.."
        - "/opt/intel/oneapi/pti/0.10/lib/cmake/pti"
        - "/opt/intel/oneapi/mkl/2025.0/lib/cmake"
        - "/opt/intel/oneapi/ipp/2022.0/lib/cmake/ipp"
        - "/opt/intel/oneapi/dpl/2022.7/lib/cmake/oneDPL"
        - "/opt/intel/oneapi/dnnl/2025.0/lib/cmake"
        - "/opt/intel/oneapi/dal/2025.0"
        - "/opt/intel/oneapi/compiler/2025.0"
      ENV{PATH}:
        - "/home/mike/.cargo/bin"
        - "/opt/intel/oneapi/vtune/2025.0/bin64"
        - "/opt/intel/oneapi/mpi/2021.14/bin"
        - "/opt/intel/oneapi/mkl/2025.0/bin"
        - "/opt/intel/oneapi/dpcpp-ct/2025.0/bin"
        - "/opt/intel/oneapi/dev-utilities/2025.0/bin"
        - "/opt/intel/oneapi/debugger/2025.0/opt/debugger/bin"
        - "/opt/intel/oneapi/compiler/2025.0/bin"
        - "/opt/intel/oneapi/advisor/2025.0/bin64"
        - "/home/mike/miniconda3/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.8.0-117-generic - x86_64
...
